from domain.errors import DomainError


class UserNotFoundError(DomainError):
    pass
