from ..errors import DomainError


class UserNotFoundError(DomainError):
    pass
